//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace TruongTieuHoc {
    
    
    public partial class Default {
        
        /// <summary>
        /// SliderArea control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::TruongTieuHoc.Display.Content.SliderArea SliderArea;
        
        /// <summary>
        /// MainBody control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::TruongTieuHoc.Display.Content.MainBody MainBody;
        
        /// <summary>
        /// RightArea control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::TruongTieuHoc.Display.Content.RightPage RightArea;
    }
}
