#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TruongTieuHoc.DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="db_TruongTieuHoc")]
	public partial class DBTruongTieuHocDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserttbl_AnhClip(tbl_AnhClip instance);
    partial void Updatetbl_AnhClip(tbl_AnhClip instance);
    partial void Deletetbl_AnhClip(tbl_AnhClip instance);
    partial void Inserttbl_WebsiteLienKet(tbl_WebsiteLienKet instance);
    partial void Updatetbl_WebsiteLienKet(tbl_WebsiteLienKet instance);
    partial void Deletetbl_WebsiteLienKet(tbl_WebsiteLienKet instance);
    partial void Inserttbl_AnhClip_ChuDe(tbl_AnhClip_ChuDe instance);
    partial void Updatetbl_AnhClip_ChuDe(tbl_AnhClip_ChuDe instance);
    partial void Deletetbl_AnhClip_ChuDe(tbl_AnhClip_ChuDe instance);
    partial void Inserttbl_Download_ChuDe(tbl_Download_ChuDe instance);
    partial void Updatetbl_Download_ChuDe(tbl_Download_ChuDe instance);
    partial void Deletetbl_Download_ChuDe(tbl_Download_ChuDe instance);
    partial void Inserttbl_Download_DanhMuc(tbl_Download_DanhMuc instance);
    partial void Updatetbl_Download_DanhMuc(tbl_Download_DanhMuc instance);
    partial void Deletetbl_Download_DanhMuc(tbl_Download_DanhMuc instance);
    partial void Inserttbl_GioiThieu(tbl_GioiThieu instance);
    partial void Updatetbl_GioiThieu(tbl_GioiThieu instance);
    partial void Deletetbl_GioiThieu(tbl_GioiThieu instance);
    partial void Inserttbl_LienHe(tbl_LienHe instance);
    partial void Updatetbl_LienHe(tbl_LienHe instance);
    partial void Deletetbl_LienHe(tbl_LienHe instance);
    partial void Inserttbl_NguoiDung(tbl_NguoiDung instance);
    partial void Updatetbl_NguoiDung(tbl_NguoiDung instance);
    partial void Deletetbl_NguoiDung(tbl_NguoiDung instance);
    #endregion
		
		public DBTruongTieuHocDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["db_TruongTieuHocConnectionString1"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DBTruongTieuHocDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBTruongTieuHocDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBTruongTieuHocDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBTruongTieuHocDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbl_AnhClip> tbl_AnhClips
		{
			get
			{
				return this.GetTable<tbl_AnhClip>();
			}
		}
		
		public System.Data.Linq.Table<tbl_WebsiteLienKet> tbl_WebsiteLienKets
		{
			get
			{
				return this.GetTable<tbl_WebsiteLienKet>();
			}
		}
		
		public System.Data.Linq.Table<tbl_AnhClip_ChuDe> tbl_AnhClip_ChuDes
		{
			get
			{
				return this.GetTable<tbl_AnhClip_ChuDe>();
			}
		}
		
		public System.Data.Linq.Table<tbl_BaiDang_ChiTiet> tbl_BaiDang_ChiTiets
		{
			get
			{
				return this.GetTable<tbl_BaiDang_ChiTiet>();
			}
		}
		
		public System.Data.Linq.Table<tbl_BaiDang_Nhom> tbl_BaiDang_Nhoms
		{
			get
			{
				return this.GetTable<tbl_BaiDang_Nhom>();
			}
		}
		
		public System.Data.Linq.Table<tbl_Download_ChuDe> tbl_Download_ChuDes
		{
			get
			{
				return this.GetTable<tbl_Download_ChuDe>();
			}
		}
		
		public System.Data.Linq.Table<tbl_Download_DanhMuc> tbl_Download_DanhMucs
		{
			get
			{
				return this.GetTable<tbl_Download_DanhMuc>();
			}
		}
		
		public System.Data.Linq.Table<tbl_GioiThieu> tbl_GioiThieus
		{
			get
			{
				return this.GetTable<tbl_GioiThieu>();
			}
		}
		
		public System.Data.Linq.Table<tbl_LienHe> tbl_LienHes
		{
			get
			{
				return this.GetTable<tbl_LienHe>();
			}
		}
		
		public System.Data.Linq.Table<tbl_NguoiDung> tbl_NguoiDungs
		{
			get
			{
				return this.GetTable<tbl_NguoiDung>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_AnhClip")]
	public partial class tbl_AnhClip : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _TieuDe;
		
		private string _MoTa;
		
		private System.Nullable<int> _IDCD;
		
		private System.Nullable<int> _ThuTu;
		
		private System.Nullable<System.DateTime> _NgayCapNhat;
		
		private System.Nullable<bool> _TrangThai;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnTieuDeChanging(string value);
    partial void OnTieuDeChanged();
    partial void OnMoTaChanging(string value);
    partial void OnMoTaChanged();
    partial void OnIDCDChanging(System.Nullable<int> value);
    partial void OnIDCDChanged();
    partial void OnThuTuChanging(System.Nullable<int> value);
    partial void OnThuTuChanged();
    partial void OnNgayCapNhatChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayCapNhatChanged();
    partial void OnTrangThaiChanging(System.Nullable<bool> value);
    partial void OnTrangThaiChanged();
    #endregion
		
		public tbl_AnhClip()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TieuDe", DbType="NVarChar(50)")]
		public string TieuDe
		{
			get
			{
				return this._TieuDe;
			}
			set
			{
				if ((this._TieuDe != value))
				{
					this.OnTieuDeChanging(value);
					this.SendPropertyChanging();
					this._TieuDe = value;
					this.SendPropertyChanged("TieuDe");
					this.OnTieuDeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoTa", DbType="NVarChar(1000)")]
		public string MoTa
		{
			get
			{
				return this._MoTa;
			}
			set
			{
				if ((this._MoTa != value))
				{
					this.OnMoTaChanging(value);
					this.SendPropertyChanging();
					this._MoTa = value;
					this.SendPropertyChanged("MoTa");
					this.OnMoTaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDCD", DbType="Int")]
		public System.Nullable<int> IDCD
		{
			get
			{
				return this._IDCD;
			}
			set
			{
				if ((this._IDCD != value))
				{
					this.OnIDCDChanging(value);
					this.SendPropertyChanging();
					this._IDCD = value;
					this.SendPropertyChanged("IDCD");
					this.OnIDCDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThuTu", DbType="Int")]
		public System.Nullable<int> ThuTu
		{
			get
			{
				return this._ThuTu;
			}
			set
			{
				if ((this._ThuTu != value))
				{
					this.OnThuTuChanging(value);
					this.SendPropertyChanging();
					this._ThuTu = value;
					this.SendPropertyChanged("ThuTu");
					this.OnThuTuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayCapNhat", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayCapNhat
		{
			get
			{
				return this._NgayCapNhat;
			}
			set
			{
				if ((this._NgayCapNhat != value))
				{
					this.OnNgayCapNhatChanging(value);
					this.SendPropertyChanging();
					this._NgayCapNhat = value;
					this.SendPropertyChanged("NgayCapNhat");
					this.OnNgayCapNhatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThai", DbType="Bit")]
		public System.Nullable<bool> TrangThai
		{
			get
			{
				return this._TrangThai;
			}
			set
			{
				if ((this._TrangThai != value))
				{
					this.OnTrangThaiChanging(value);
					this.SendPropertyChanging();
					this._TrangThai = value;
					this.SendPropertyChanged("TrangThai");
					this.OnTrangThaiChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_WebsiteLienKet")]
	public partial class tbl_WebsiteLienKet : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDW;
		
		private string _TieuDeW;
		
		private string _MoTaW;
		
		private System.Nullable<System.DateTime> _NgayCapNhat;
		
		private string _Link;
		
		private System.Nullable<int> _ThuTu;
		
		private System.Nullable<bool> _TrangThai;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDWChanging(int value);
    partial void OnIDWChanged();
    partial void OnTieuDeWChanging(string value);
    partial void OnTieuDeWChanged();
    partial void OnMoTaWChanging(string value);
    partial void OnMoTaWChanged();
    partial void OnNgayCapNhatChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayCapNhatChanged();
    partial void OnLinkChanging(string value);
    partial void OnLinkChanged();
    partial void OnThuTuChanging(System.Nullable<int> value);
    partial void OnThuTuChanged();
    partial void OnTrangThaiChanging(System.Nullable<bool> value);
    partial void OnTrangThaiChanged();
    #endregion
		
		public tbl_WebsiteLienKet()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDW", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDW
		{
			get
			{
				return this._IDW;
			}
			set
			{
				if ((this._IDW != value))
				{
					this.OnIDWChanging(value);
					this.SendPropertyChanging();
					this._IDW = value;
					this.SendPropertyChanged("IDW");
					this.OnIDWChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TieuDeW", DbType="NVarChar(50)")]
		public string TieuDeW
		{
			get
			{
				return this._TieuDeW;
			}
			set
			{
				if ((this._TieuDeW != value))
				{
					this.OnTieuDeWChanging(value);
					this.SendPropertyChanging();
					this._TieuDeW = value;
					this.SendPropertyChanged("TieuDeW");
					this.OnTieuDeWChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoTaW", DbType="NVarChar(1000)")]
		public string MoTaW
		{
			get
			{
				return this._MoTaW;
			}
			set
			{
				if ((this._MoTaW != value))
				{
					this.OnMoTaWChanging(value);
					this.SendPropertyChanging();
					this._MoTaW = value;
					this.SendPropertyChanged("MoTaW");
					this.OnMoTaWChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayCapNhat", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayCapNhat
		{
			get
			{
				return this._NgayCapNhat;
			}
			set
			{
				if ((this._NgayCapNhat != value))
				{
					this.OnNgayCapNhatChanging(value);
					this.SendPropertyChanging();
					this._NgayCapNhat = value;
					this.SendPropertyChanged("NgayCapNhat");
					this.OnNgayCapNhatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Link", DbType="NVarChar(200)")]
		public string Link
		{
			get
			{
				return this._Link;
			}
			set
			{
				if ((this._Link != value))
				{
					this.OnLinkChanging(value);
					this.SendPropertyChanging();
					this._Link = value;
					this.SendPropertyChanged("Link");
					this.OnLinkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThuTu", DbType="Int")]
		public System.Nullable<int> ThuTu
		{
			get
			{
				return this._ThuTu;
			}
			set
			{
				if ((this._ThuTu != value))
				{
					this.OnThuTuChanging(value);
					this.SendPropertyChanging();
					this._ThuTu = value;
					this.SendPropertyChanged("ThuTu");
					this.OnThuTuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThai", DbType="Bit")]
		public System.Nullable<bool> TrangThai
		{
			get
			{
				return this._TrangThai;
			}
			set
			{
				if ((this._TrangThai != value))
				{
					this.OnTrangThaiChanging(value);
					this.SendPropertyChanging();
					this._TrangThai = value;
					this.SendPropertyChanged("TrangThai");
					this.OnTrangThaiChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_AnhClip_ChuDe")]
	public partial class tbl_AnhClip_ChuDe : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDCD;
		
		private string _TenCD;
		
		private string _MoTaChuDe;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDCDChanging(int value);
    partial void OnIDCDChanged();
    partial void OnTenCDChanging(string value);
    partial void OnTenCDChanged();
    partial void OnMoTaChuDeChanging(string value);
    partial void OnMoTaChuDeChanged();
    #endregion
		
		public tbl_AnhClip_ChuDe()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDCD", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDCD
		{
			get
			{
				return this._IDCD;
			}
			set
			{
				if ((this._IDCD != value))
				{
					this.OnIDCDChanging(value);
					this.SendPropertyChanging();
					this._IDCD = value;
					this.SendPropertyChanged("IDCD");
					this.OnIDCDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenCD", DbType="NVarChar(200)")]
		public string TenCD
		{
			get
			{
				return this._TenCD;
			}
			set
			{
				if ((this._TenCD != value))
				{
					this.OnTenCDChanging(value);
					this.SendPropertyChanging();
					this._TenCD = value;
					this.SendPropertyChanged("TenCD");
					this.OnTenCDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoTaChuDe", DbType="NVarChar(1000)")]
		public string MoTaChuDe
		{
			get
			{
				return this._MoTaChuDe;
			}
			set
			{
				if ((this._MoTaChuDe != value))
				{
					this.OnMoTaChuDeChanging(value);
					this.SendPropertyChanging();
					this._MoTaChuDe = value;
					this.SendPropertyChanged("MoTaChuDe");
					this.OnMoTaChuDeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_BaiDang_ChiTiet")]
	public partial class tbl_BaiDang_ChiTiet
	{
		
		private int _IDBD;
		
		private string _TieuDeBD;
		
		private string _TomTatBD;
		
		private string _NoiDungBD;
		
		private string _HinhAnhBD;
		
		private System.Nullable<bool> _MoiNhatBD;
		
		private System.Nullable<int> _LuotXemBD;
		
		private System.Nullable<System.DateTime> _NgayDangBD;
		
		private System.Nullable<int> _IDNguoiDang;
		
		private System.Nullable<int> _ThuTu;
		
		private System.Nullable<bool> _TrangThai;
		
		private System.Nullable<int> _IDNhom;
		
		public tbl_BaiDang_ChiTiet()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDBD", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int IDBD
		{
			get
			{
				return this._IDBD;
			}
			set
			{
				if ((this._IDBD != value))
				{
					this._IDBD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TieuDeBD", DbType="NVarChar(50)")]
		public string TieuDeBD
		{
			get
			{
				return this._TieuDeBD;
			}
			set
			{
				if ((this._TieuDeBD != value))
				{
					this._TieuDeBD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TomTatBD", DbType="NVarChar(4000)")]
		public string TomTatBD
		{
			get
			{
				return this._TomTatBD;
			}
			set
			{
				if ((this._TomTatBD != value))
				{
					this._TomTatBD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDungBD", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string NoiDungBD
		{
			get
			{
				return this._NoiDungBD;
			}
			set
			{
				if ((this._NoiDungBD != value))
				{
					this._NoiDungBD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HinhAnhBD", DbType="NVarChar(200)")]
		public string HinhAnhBD
		{
			get
			{
				return this._HinhAnhBD;
			}
			set
			{
				if ((this._HinhAnhBD != value))
				{
					this._HinhAnhBD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoiNhatBD", DbType="Bit")]
		public System.Nullable<bool> MoiNhatBD
		{
			get
			{
				return this._MoiNhatBD;
			}
			set
			{
				if ((this._MoiNhatBD != value))
				{
					this._MoiNhatBD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LuotXemBD", DbType="Int")]
		public System.Nullable<int> LuotXemBD
		{
			get
			{
				return this._LuotXemBD;
			}
			set
			{
				if ((this._LuotXemBD != value))
				{
					this._LuotXemBD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayDangBD", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayDangBD
		{
			get
			{
				return this._NgayDangBD;
			}
			set
			{
				if ((this._NgayDangBD != value))
				{
					this._NgayDangBD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDNguoiDang", DbType="Int")]
		public System.Nullable<int> IDNguoiDang
		{
			get
			{
				return this._IDNguoiDang;
			}
			set
			{
				if ((this._IDNguoiDang != value))
				{
					this._IDNguoiDang = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThuTu", DbType="Int")]
		public System.Nullable<int> ThuTu
		{
			get
			{
				return this._ThuTu;
			}
			set
			{
				if ((this._ThuTu != value))
				{
					this._ThuTu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThai", DbType="Bit")]
		public System.Nullable<bool> TrangThai
		{
			get
			{
				return this._TrangThai;
			}
			set
			{
				if ((this._TrangThai != value))
				{
					this._TrangThai = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDNhom", DbType="Int")]
		public System.Nullable<int> IDNhom
		{
			get
			{
				return this._IDNhom;
			}
			set
			{
				if ((this._IDNhom != value))
				{
					this._IDNhom = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_BaiDang_Nhom")]
	public partial class tbl_BaiDang_Nhom
	{
		
		private int _ID;
		
		private string _IDNhom;
		
		private string _TenNhom;
		
		private System.Nullable<bool> _TrangThai;
		
		public tbl_BaiDang_Nhom()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDNhom", DbType="VarChar(30)")]
		public string IDNhom
		{
			get
			{
				return this._IDNhom;
			}
			set
			{
				if ((this._IDNhom != value))
				{
					this._IDNhom = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNhom", DbType="NVarChar(100)")]
		public string TenNhom
		{
			get
			{
				return this._TenNhom;
			}
			set
			{
				if ((this._TenNhom != value))
				{
					this._TenNhom = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThai", DbType="Bit")]
		public System.Nullable<bool> TrangThai
		{
			get
			{
				return this._TrangThai;
			}
			set
			{
				if ((this._TrangThai != value))
				{
					this._TrangThai = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Download_ChuDe")]
	public partial class tbl_Download_ChuDe : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDCD;
		
		private string _TieuDeCD;
		
		private System.Nullable<bool> _TrangThaiCD;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDCDChanging(int value);
    partial void OnIDCDChanged();
    partial void OnTieuDeCDChanging(string value);
    partial void OnTieuDeCDChanged();
    partial void OnTrangThaiCDChanging(System.Nullable<bool> value);
    partial void OnTrangThaiCDChanged();
    #endregion
		
		public tbl_Download_ChuDe()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDCD", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDCD
		{
			get
			{
				return this._IDCD;
			}
			set
			{
				if ((this._IDCD != value))
				{
					this.OnIDCDChanging(value);
					this.SendPropertyChanging();
					this._IDCD = value;
					this.SendPropertyChanged("IDCD");
					this.OnIDCDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TieuDeCD", DbType="NVarChar(50)")]
		public string TieuDeCD
		{
			get
			{
				return this._TieuDeCD;
			}
			set
			{
				if ((this._TieuDeCD != value))
				{
					this.OnTieuDeCDChanging(value);
					this.SendPropertyChanging();
					this._TieuDeCD = value;
					this.SendPropertyChanged("TieuDeCD");
					this.OnTieuDeCDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThaiCD", DbType="Bit")]
		public System.Nullable<bool> TrangThaiCD
		{
			get
			{
				return this._TrangThaiCD;
			}
			set
			{
				if ((this._TrangThaiCD != value))
				{
					this.OnTrangThaiCDChanging(value);
					this.SendPropertyChanging();
					this._TrangThaiCD = value;
					this.SendPropertyChanged("TrangThaiCD");
					this.OnTrangThaiCDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Download_DanhMuc")]
	public partial class tbl_Download_DanhMuc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDDM;
		
		private string _TieuDeDM;
		
		private string _LinkDownload;
		
		private System.Nullable<System.DateTime> _NgayUpload;
		
		private System.Nullable<int> _ThuTu;
		
		private System.Nullable<bool> _TrangThai;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDDMChanging(int value);
    partial void OnIDDMChanged();
    partial void OnTieuDeDMChanging(string value);
    partial void OnTieuDeDMChanged();
    partial void OnLinkDownloadChanging(string value);
    partial void OnLinkDownloadChanged();
    partial void OnNgayUploadChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayUploadChanged();
    partial void OnThuTuChanging(System.Nullable<int> value);
    partial void OnThuTuChanged();
    partial void OnTrangThaiChanging(System.Nullable<bool> value);
    partial void OnTrangThaiChanged();
    #endregion
		
		public tbl_Download_DanhMuc()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDDM", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDDM
		{
			get
			{
				return this._IDDM;
			}
			set
			{
				if ((this._IDDM != value))
				{
					this.OnIDDMChanging(value);
					this.SendPropertyChanging();
					this._IDDM = value;
					this.SendPropertyChanged("IDDM");
					this.OnIDDMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TieuDeDM", DbType="NVarChar(50)")]
		public string TieuDeDM
		{
			get
			{
				return this._TieuDeDM;
			}
			set
			{
				if ((this._TieuDeDM != value))
				{
					this.OnTieuDeDMChanging(value);
					this.SendPropertyChanging();
					this._TieuDeDM = value;
					this.SendPropertyChanged("TieuDeDM");
					this.OnTieuDeDMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LinkDownload", DbType="NVarChar(200)")]
		public string LinkDownload
		{
			get
			{
				return this._LinkDownload;
			}
			set
			{
				if ((this._LinkDownload != value))
				{
					this.OnLinkDownloadChanging(value);
					this.SendPropertyChanging();
					this._LinkDownload = value;
					this.SendPropertyChanged("LinkDownload");
					this.OnLinkDownloadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayUpload", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayUpload
		{
			get
			{
				return this._NgayUpload;
			}
			set
			{
				if ((this._NgayUpload != value))
				{
					this.OnNgayUploadChanging(value);
					this.SendPropertyChanging();
					this._NgayUpload = value;
					this.SendPropertyChanged("NgayUpload");
					this.OnNgayUploadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThuTu", DbType="Int")]
		public System.Nullable<int> ThuTu
		{
			get
			{
				return this._ThuTu;
			}
			set
			{
				if ((this._ThuTu != value))
				{
					this.OnThuTuChanging(value);
					this.SendPropertyChanging();
					this._ThuTu = value;
					this.SendPropertyChanged("ThuTu");
					this.OnThuTuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThai", DbType="Bit")]
		public System.Nullable<bool> TrangThai
		{
			get
			{
				return this._TrangThai;
			}
			set
			{
				if ((this._TrangThai != value))
				{
					this.OnTrangThaiChanging(value);
					this.SendPropertyChanging();
					this._TrangThai = value;
					this.SendPropertyChanged("TrangThai");
					this.OnTrangThaiChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_GioiThieu")]
	public partial class tbl_GioiThieu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _TieuDeGT;
		
		private string _NoiDungGT;
		
		private string _HinhAnhGT;
		
		private System.Nullable<System.DateTime> _NgayCapNhatGT;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnTieuDeGTChanging(string value);
    partial void OnTieuDeGTChanged();
    partial void OnNoiDungGTChanging(string value);
    partial void OnNoiDungGTChanged();
    partial void OnHinhAnhGTChanging(string value);
    partial void OnHinhAnhGTChanged();
    partial void OnNgayCapNhatGTChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayCapNhatGTChanged();
    #endregion
		
		public tbl_GioiThieu()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TieuDeGT", DbType="NVarChar(50)")]
		public string TieuDeGT
		{
			get
			{
				return this._TieuDeGT;
			}
			set
			{
				if ((this._TieuDeGT != value))
				{
					this.OnTieuDeGTChanging(value);
					this.SendPropertyChanging();
					this._TieuDeGT = value;
					this.SendPropertyChanged("TieuDeGT");
					this.OnTieuDeGTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDungGT", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string NoiDungGT
		{
			get
			{
				return this._NoiDungGT;
			}
			set
			{
				if ((this._NoiDungGT != value))
				{
					this.OnNoiDungGTChanging(value);
					this.SendPropertyChanging();
					this._NoiDungGT = value;
					this.SendPropertyChanged("NoiDungGT");
					this.OnNoiDungGTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HinhAnhGT", DbType="NVarChar(200)")]
		public string HinhAnhGT
		{
			get
			{
				return this._HinhAnhGT;
			}
			set
			{
				if ((this._HinhAnhGT != value))
				{
					this.OnHinhAnhGTChanging(value);
					this.SendPropertyChanging();
					this._HinhAnhGT = value;
					this.SendPropertyChanged("HinhAnhGT");
					this.OnHinhAnhGTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayCapNhatGT", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayCapNhatGT
		{
			get
			{
				return this._NgayCapNhatGT;
			}
			set
			{
				if ((this._NgayCapNhatGT != value))
				{
					this.OnNgayCapNhatGTChanging(value);
					this.SendPropertyChanging();
					this._NgayCapNhatGT = value;
					this.SendPropertyChanged("NgayCapNhatGT");
					this.OnNgayCapNhatGTChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_LienHe")]
	public partial class tbl_LienHe : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _HoTen;
		
		private string _Email;
		
		private string _TinNhan;
		
		private System.Nullable<bool> _TrangThai;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnTinNhanChanging(string value);
    partial void OnTinNhanChanged();
    partial void OnTrangThaiChanging(System.Nullable<bool> value);
    partial void OnTrangThaiChanged();
    #endregion
		
		public tbl_LienHe()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(200)")]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this.OnHoTenChanging(value);
					this.SendPropertyChanging();
					this._HoTen = value;
					this.SendPropertyChanged("HoTen");
					this.OnHoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(1000)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TinNhan", DbType="NVarChar(4000)")]
		public string TinNhan
		{
			get
			{
				return this._TinNhan;
			}
			set
			{
				if ((this._TinNhan != value))
				{
					this.OnTinNhanChanging(value);
					this.SendPropertyChanging();
					this._TinNhan = value;
					this.SendPropertyChanged("TinNhan");
					this.OnTinNhanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThai", DbType="Bit")]
		public System.Nullable<bool> TrangThai
		{
			get
			{
				return this._TrangThai;
			}
			set
			{
				if ((this._TrangThai != value))
				{
					this.OnTrangThaiChanging(value);
					this.SendPropertyChanging();
					this._TrangThai = value;
					this.SendPropertyChanged("TrangThai");
					this.OnTrangThaiChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_NguoiDung")]
	public partial class tbl_NguoiDung : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDAdmin;
		
		private string _TaiKhoan;
		
		private string _MatKhau;
		
		private string _Ho;
		
		private string _Ten;
		
		private System.Nullable<bool> _GioiTinh;
		
		private System.Nullable<System.DateTime> _NgaySinh;
		
		private string _DiaChi;
		
		private string _SDT;
		
		private string _ChucVu;
		
		private System.Nullable<bool> _QuyenAdmin;
		
		private System.Nullable<bool> _TrangThai;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDAdminChanging(int value);
    partial void OnIDAdminChanged();
    partial void OnTaiKhoanChanging(string value);
    partial void OnTaiKhoanChanged();
    partial void OnMatKhauChanging(string value);
    partial void OnMatKhauChanged();
    partial void OnHoChanging(string value);
    partial void OnHoChanged();
    partial void OnTenChanging(string value);
    partial void OnTenChanged();
    partial void OnGioiTinhChanging(System.Nullable<bool> value);
    partial void OnGioiTinhChanged();
    partial void OnNgaySinhChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaySinhChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnChucVuChanging(string value);
    partial void OnChucVuChanged();
    partial void OnQuyenAdminChanging(System.Nullable<bool> value);
    partial void OnQuyenAdminChanged();
    partial void OnTrangThaiChanging(System.Nullable<bool> value);
    partial void OnTrangThaiChanged();
    #endregion
		
		public tbl_NguoiDung()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDAdmin", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDAdmin
		{
			get
			{
				return this._IDAdmin;
			}
			set
			{
				if ((this._IDAdmin != value))
				{
					this.OnIDAdminChanging(value);
					this.SendPropertyChanging();
					this._IDAdmin = value;
					this.SendPropertyChanged("IDAdmin");
					this.OnIDAdminChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaiKhoan", DbType="VarChar(50)")]
		public string TaiKhoan
		{
			get
			{
				return this._TaiKhoan;
			}
			set
			{
				if ((this._TaiKhoan != value))
				{
					this.OnTaiKhoanChanging(value);
					this.SendPropertyChanging();
					this._TaiKhoan = value;
					this.SendPropertyChanged("TaiKhoan");
					this.OnTaiKhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="VarChar(50)")]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this.OnMatKhauChanging(value);
					this.SendPropertyChanging();
					this._MatKhau = value;
					this.SendPropertyChanged("MatKhau");
					this.OnMatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ho", DbType="NVarChar(30)")]
		public string Ho
		{
			get
			{
				return this._Ho;
			}
			set
			{
				if ((this._Ho != value))
				{
					this.OnHoChanging(value);
					this.SendPropertyChanging();
					this._Ho = value;
					this.SendPropertyChanged("Ho");
					this.OnHoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten", DbType="NVarChar(15)")]
		public string Ten
		{
			get
			{
				return this._Ten;
			}
			set
			{
				if ((this._Ten != value))
				{
					this.OnTenChanging(value);
					this.SendPropertyChanging();
					this._Ten = value;
					this.SendPropertyChanged("Ten");
					this.OnTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="Bit")]
		public System.Nullable<bool> GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this.OnGioiTinhChanging(value);
					this.SendPropertyChanging();
					this._GioiTinh = value;
					this.SendPropertyChanged("GioiTinh");
					this.OnGioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(4000)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="VarChar(15)")]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChucVu", DbType="VarChar(40)")]
		public string ChucVu
		{
			get
			{
				return this._ChucVu;
			}
			set
			{
				if ((this._ChucVu != value))
				{
					this.OnChucVuChanging(value);
					this.SendPropertyChanging();
					this._ChucVu = value;
					this.SendPropertyChanged("ChucVu");
					this.OnChucVuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuyenAdmin", DbType="Bit")]
		public System.Nullable<bool> QuyenAdmin
		{
			get
			{
				return this._QuyenAdmin;
			}
			set
			{
				if ((this._QuyenAdmin != value))
				{
					this.OnQuyenAdminChanging(value);
					this.SendPropertyChanging();
					this._QuyenAdmin = value;
					this.SendPropertyChanged("QuyenAdmin");
					this.OnQuyenAdminChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThai", DbType="Bit")]
		public System.Nullable<bool> TrangThai
		{
			get
			{
				return this._TrangThai;
			}
			set
			{
				if ((this._TrangThai != value))
				{
					this.OnTrangThaiChanging(value);
					this.SendPropertyChanging();
					this._TrangThai = value;
					this.SendPropertyChanged("TrangThai");
					this.OnTrangThaiChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
